### ISSUE TITLE
I encountered some problems

### ISSUE THREAD

**Issue by xiaotujinbnb** [rpetrich/callander#5]
Great developer, I'm trying to use seccomp on an andorid application to filter oepnat system calls. I use sigaction to register a handler that handles the SIGSYS signal. I make modifications to the parameters and return values in the handler. Everything works fine at runtime but when I The application I encountered also uses sigaction and triggering SIGSYS again in the seccomp handler in the application will cause the program to directly abort Fatal error: 31 (Bad system call). How should I solve this problem?

**Comment by rpetrich** [comment]
You should also intercept rt_sigaction so that when the application attempts to register its handler SIGSYS handler with the kernel it will be emulated in your code instead. You can store the handler to call into it later, or simply discard the application's attempt. This is implemented in intercept.c: https://github.com/rpetrich/callander/blob/5ac21f5c36c1adc98a96cd96bbf8189fa2461039/src/intercept.c#L282-L321

**Comment by xiaotujinbnb** [comment]
Thanks for your reply, it solved my problem

**Comment by rpetrich** [comment]
Glad you got it worked out.
